<?php require VIEWS_PATH . 'includes/header.phtml'?>

    <div class="container">
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
            <h1>Projeto 01 - Contatos</h1>
        </div>

        <div class="row">
            <form>
                <div class="form-group">
                    <label for="exampleInputNome">Nome</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Nome">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>

                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Check me out
                    </label>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>

    </div> <!-- /container -->

<?php require VIEWS_PATH . 'includes/footer.phtml'?>