<?php require VIEWS_PATH . 'includes/header.phtml'?>

    <div class="container">
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
            <h1>Projeto 01 - OO</h1>
            <p>Prójeto Prático usando PHP OO</p>
            <p>
                <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">Mais Detalhes</a>
            </p>
        </div>
    </div> <!-- /container -->

    <div class="container">
        <div class="row">
            <?php foreach ($this->products as $product): ?>
            <div class="col-md-4">
                <img src="https://via.placeholder.com/350x150?text=<?= $product['name'];?>" alt="">
                <h4><?= $product['name'];?></h4>
                <p><?= $product['description'];?></p>
                <p><?= $product['price'];?></p>
            </div>
            <?php endforeach;?>
        </div>
    </div>

<?php require VIEWS_PATH . 'includes/footer.phtml'?>