<?php require VIEWS_PATH . 'includes/header.phtml'?>

    <div class="container">
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
            <h1>Projeto 01 - OO</h1>
            <p>Prójeto Prático usando PHP OO</p>
            <p>
                <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">Mais Detalhes</a>
            </p>
        </div>

    </div> <!-- /container -->

<?php require VIEWS_PATH . 'includes/footer.phtml'?>