<?php require VIEWS_PATH . 'includes/header.phtml' ?>

    <div class="container">
        <div class="col-md-12">
            <h1>Editar despesa</h1>
            <hr>
        </div>

        <div class="col-md-12">
            <form method="post" action="<?=HOME?>/myexpenses/edit/<?=$this->expense['id'];?>">
                <div class="form-group">
                    <label for="valorgasto">Valor Gasto</label>
                    <input type="text"
                           class="form-control"
                           name="value"
                           id="valorgasto"
                           placeholder="Valor Gasto"
                        value="<?php echo $this->expense['value'];?>">
                </div>

                <div class="form-group">
                    <label for="categories_id">Categoria</label>
                    <select name="categories_id" id="categories_id">
                        <?php foreach ($this->categories as $c){ ?>
                            <option value="<?=$c['id']?>"
                                <?php if($c['id'] == $this->expense['categories_id']):?>
                                    selected
                                <?php endif;?>
                            ><?=$c['name']?>
                            </option>
                        <?php } ?>
                    </select>
                </div>

                <div class="form-group">
                    <label for="users_id">Usuário</label>
                    <select name="users_id" id="users_id">
                        <?php foreach ($this->users as $u){ ?>
                            <option value="<?=$u['id']?>"
                                <?php if($c['id'] == $this->expense['users_id']):?>
                                    selected
                                <?php endif;?>
                            ><?=$u['first_name']?></option>
                        <?php } ?>
                    </select>
                </div>

                <div class="form-group">
                    <label for="description">Descrição</label>
                    <textarea class="form-control" name="description" id="description" cols="30" rows="10">
                        <?php echo $this->expense['description'];?>
                    </textarea>
                </div>

                <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Despesa</button>
            </form>
        </div>
    </div>
<?php require VIEWS_PATH . 'includes/footer.phtml' ?>