<?php require VIEWS_PATH . 'includes/header.phtml' ?>

    <div class="container">
        <div class="col-md-12">
            <h1>Cadastrar nova despesa</h1>
            <hr>
        </div>

        <div class="col-md-12">
            <form method="post" action="<?=HOME?>/myexpenses/new">
                <div class="form-group">
                    <label for="valorgasto">Valor Gasto</label>
                    <input type="text"
                           class="form-control"
                           name="value"
                           id="valorgasto"
                           placeholder="Valor Gasto">
                </div>

                <div class="form-group">
                    <label for="categories_id">Categoria</label>
                    <select name="categories_id" id="categories_id">
                    <?php foreach ($this->categories as $c){ ?>
                        <option value="<?=$c['id']?>"><?=$c['name']?></option>
                        <?php } ?>
                    </select>
                </div>

                <div class="form-group">
                    <label for="users_id">Usuário</label>
                    <select name="users_id" id="users_id">
                        <?php foreach ($this->users as $u){ ?>
                            <option value="<?=$u['id']?>"><?=$u['first_name']?></option>
                        <?php } ?>
                    </select>
                </div>

                <div class="form-group">
                    <label for="description">Descrição</label>
                    <textarea class="form-control" name="description" id="description" cols="30" rows="10"></textarea>
                </div>

                <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Despesa</button>
            </form>
        </div>
    </div>
<?php require VIEWS_PATH . 'includes/footer.phtml' ?>