<?php require VIEWS_PATH . 'includes/header.phtml' ?>

    <div class="container">
        <div class="col-md-12">
            <h1>Cadastrar nova despesa</h1>
            <hr>
        </div>

        <div class="col-md-12">
            <form method="post" action="<?=HOME?>/myexpenses/new">
                <div class="form-group">
                    <label for="valorgasto">Valor Gasto</label>
                    <input type="text"
                           class="form-control"
                           name="price"
                           id="valorgasto"
                           placeholder="Valor Gasto">
                </div>
                <div class="form-group">
                    <label for="description">Descrição</label>
                    <textarea class="form-control" name="description" id="description" cols="30" rows="10"></textarea>
                </div>

                <button type="submit" class="btn btn-success btn-lg pull-right">Salvar Despesa</button>
            </form>
        </div>
    </div>
<?php require VIEWS_PATH . 'includes/footer.phtml' ?>