<?php require VIEWS_PATH . 'includes/header.phtml'?>

    <div class="container">
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
            <h1>Gerenciador de Gastos Pessoais</h1>
            <p>Projeto 3 criado - POO PHP</p>
            <p>
                <a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">Mais Detalhes</a>
            </p>
        </div>
    </div> <!-- /container -->

    <div class="container">
        <div class="row">

        </div>
    </div>

<?php require VIEWS_PATH . 'includes/footer.phtml'?>