<?php require VIEWS_PATH . 'includes/header.phtml' ?>

    <div class="container">
        <div class="col-md-12">
            <div class="col-md-6">
                <img src="https://via.placeholder.com/500x350?text=<?= $this->product['name']; ?>" alt="">
            </div>
            <div class="col-md-6">
                <h4><a href="<?= HOME ?>/product/<?= $this->product['id'] ?>"><?= $this->product['name']; ?></a></h4>
                <p><?= $this->product['description']; ?></p>
                <p>R$ <?= $this->product['price']; ?></p>
            </div>
        </div>
    </div>

<?php require VIEWS_PATH . 'includes/footer.phtml' ?>